SETTING = """SET @rownum:=0"""

PROCESS_NUM = """SELECT CD_VAL1 FROM TB_CFG_CODE WHERE CD_ID = 'PROCESS_NUM'"""

TOTAL_LIST = """
SELECT Z.* FROM (
SELECT @ROWNUM := @ROWNUM + 1 AS ROWNUM, A.* FROM(
#데이터망 IP
SELECT A.IP_NO AS SEQ_NO,A.LINE_NO, '' AS INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.LINE_IP,A.LINE_PORT, A.STATUS, 'D' AS TYPE
FROM TB_POP_D_IP A
INNER JOIN TB_POP_D_LINE B
ON A.LINE_NO=B.LINE_NO
INNER JOIN (SELECT CITY_NO FROM TB_POP_CITY WHERE DEL_DT IS NULL) C
ON B.POP_SRC_NO=C.CITY_NO OR B.POP_DST_NO=C.CITY_NO
GROUP BY IP_NO,LINE_NO,LINE_IP,LINE_PORT,STATUS
UNION ALL
#인터넷망 IP
SELECT A.LINE_D_NO AS SEQ_NO,C.LINE_NO,A.INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.SRC_LINE_IP AS LINE_IP, '' LINE_PORT, A.STATUS, 'I' AS TYPE
FROM TB_POP_I_LINE_DETAIL A
INNER JOIN TB_POP_I_CONN B
ON A.INTERNET_LINE_NO=B.INTERNET_LINE_NO
INNER JOIN (SELECT * FROM TB_POP_I_LINE WHERE DEL_DT IS NULL ) C
ON B.LINE_NO=C.LINE_NO
UNION ALL
#이벤트망 IP
SELECT B.LINE_DETAIL_NO AS SEQ_NO, B.LINE_NO,'' AS INTERNET_LINE_NO,B.LINE_GRP_NO,B.LINE_IP, B.LINE_PORT, B.STATUS, 'E' AS TYPE
FROM (SELECT LINE_NO,LINE_GRP_NO, LINE_NM FROM TB_EVT_LINE WHERE DEL_DT IS NULL) A
INNER JOIN TB_EVT_LINE_DETAIL B
ON A.LINE_GRP_NO=B.LINE_GRP_NO AND A.LINE_NO=B.LINE_NO)A
)Z WHERE MOD(z.ROWNUM, {0}) = {1}
"""

TOTAL_COUNT = """
SELECT COUNT(LINE_IP) FROM(
#데이터망 IP
SELECT A.IP_NO AS SEQ_NO,A.LINE_NO, '' AS INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.LINE_IP,A.LINE_PORT, A.STATUS, 'D' AS TYPE
FROM TB_POP_D_IP A
INNER JOIN TB_POP_D_LINE B
ON A.LINE_NO=B.LINE_NO
INNER JOIN (SELECT CITY_NO FROM TB_POP_CITY WHERE DEL_DT IS NULL) C
ON B.POP_SRC_NO=C.CITY_NO OR B.POP_DST_NO=C.CITY_NO
GROUP BY IP_NO,LINE_NO,LINE_IP,LINE_PORT,STATUS
UNION ALL
#인터넷망 IP
SELECT A.LINE_D_NO AS SEQ_NO,C.LINE_NO,A.INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.SRC_LINE_IP AS LINE_IP, '' LINE_PORT, A.STATUS, 'I' AS TYPE
FROM TB_POP_I_LINE_DETAIL A
INNER JOIN TB_POP_I_CONN B
ON A.INTERNET_LINE_NO=B.INTERNET_LINE_NO
INNER JOIN (SELECT * FROM TB_POP_I_LINE WHERE DEL_DT IS NULL ) C
ON B.LINE_NO=C.LINE_NO
UNION ALL
#이벤트망 IP
SELECT B.LINE_DETAIL_NO AS SEQ_NO, B.LINE_NO,'' AS INTERNET_LINE_NO,B.LINE_GRP_NO,B.LINE_IP, B.LINE_PORT, B.STATUS, 'E' AS TYPE
FROM (SELECT LINE_NO,LINE_GRP_NO, LINE_NM FROM TB_EVT_LINE WHERE DEL_DT IS NULL) A
INNER JOIN TB_EVT_LINE_DETAIL B
ON A.LINE_GRP_NO=B.LINE_GRP_NO AND A.LINE_NO=B.LINE_NO)A
"""

IP_LIST = """
SELECT DISTINCT LINE_IP, TYPE FROM(
#데이터망 IP
SELECT A.IP_NO AS SEQ_NO,A.LINE_NO, '' AS INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.LINE_IP,A.LINE_PORT, A.STATUS, 'D' AS TYPE
FROM TB_POP_D_IP A
INNER JOIN TB_POP_D_LINE B
ON A.LINE_NO=B.LINE_NO
INNER JOIN (SELECT CITY_NO FROM TB_POP_CITY WHERE DEL_DT IS NULL) C
ON B.POP_SRC_NO=C.CITY_NO OR B.POP_DST_NO=C.CITY_NO
GROUP BY IP_NO,LINE_NO,LINE_IP,LINE_PORT,STATUS
UNION ALL
#인터넷망 IP
SELECT A.LINE_D_NO AS SEQ_NO,C.LINE_NO,A.INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.SRC_LINE_IP AS LINE_IP, '' LINE_PORT, A.STATUS, 'I' AS TYPE
FROM TB_POP_I_LINE_DETAIL A
INNER JOIN TB_POP_I_CONN B
ON A.INTERNET_LINE_NO=B.INTERNET_LINE_NO
INNER JOIN (SELECT * FROM TB_POP_I_LINE WHERE DEL_DT IS NULL ) C
ON B.LINE_NO=C.LINE_NO
UNION ALL
#이벤트망 IP
SELECT B.LINE_DETAIL_NO AS SEQ_NO, B.LINE_NO,'' AS INTERNET_LINE_NO,B.LINE_GRP_NO,B.LINE_IP, B.LINE_PORT, B.STATUS, 'E' AS TYPE
FROM (SELECT LINE_NO,LINE_GRP_NO, LINE_NM FROM TB_EVT_LINE WHERE DEL_DT IS NULL) A
INNER JOIN TB_EVT_LINE_DETAIL B
ON A.LINE_GRP_NO=B.LINE_GRP_NO AND A.LINE_NO=B.LINE_NO)A
"""

DATA_COUNT = """
SELECT COUNT(*) FROM
(SELECT A.IP_NO AS SEQ_NO, A.LINE_NO, '' AS INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.LINE_IP,A.LINE_PORT, A.STATUS, 'D' AS TYPE
FROM TB_POP_D_IP A
INNER JOIN TB_POP_D_LINE B
ON A.LINE_NO=B.LINE_NO
INNER JOIN (SELECT CITY_NO FROM TB_POP_CITY WHERE DEL_DT IS NULL) C
ON B.POP_SRC_NO=C.CITY_NO OR B.POP_DST_NO=C.CITY_NO
GROUP BY IP_NO,LINE_NO,LINE_IP,LINE_PORT,STATUS) C
"""

INTERNET_COUNT = """
SELECT COUNT(*) FROM
(SELECT A.LINE_D_NO AS SEQ_NO,C.LINE_NO,A.INTERNET_LINE_NO,'' AS LINE_GRP_NO,A.SRC_LINE_IP AS LINE_IP, '' LINE_PORT, A.STATUS, 'I' AS TYPE
FROM TB_POP_I_LINE_DETAIL A
INNER JOIN TB_POP_I_CONN B
ON A.INTERNET_LINE_NO=B.INTERNET_LINE_NO
INNER JOIN (SELECT * FROM TB_POP_I_LINE WHERE DEL_DT IS NULL ) C
ON B.LINE_NO=C.LINE_NO) C
"""

EVT_COUNT = """
SELECT COUNT(*) FROM
(SELECT B.LINE_DETAIL_NO AS SEQ_NO, B.LINE_NO,'' AS INTERNET_LINE_NO,B.LINE_GRP_NO,B.LINE_IP, B.LINE_PORT, B.STATUS, 'E' AS TYPE
FROM (SELECT LINE_NO,LINE_GRP_NO, LINE_NM FROM TB_EVT_LINE WHERE DEL_DT IS NULL) A
INNER JOIN TB_EVT_LINE_DETAIL B
ON A.LINE_GRP_NO=B.LINE_GRP_NO AND A.LINE_NO=B.LINE_NO)C
"""

DATA_INSERT = """\
INSERT INTO TB_POP_D_LOG_HIST
(CRT_DT, SUCCESS_CNT, LINE_RESP_MIN, LINE_RESP_AVG, LINE_RESP_MAX, STATUS, USER_CHK, LINE_NO, LINE_IP) 
VALUES('{0}', {1}, CONCAT({2}, "ms"), CONCAT({3}, "ms"), CONCAT({4}, "ms"), {5}, '{6}', {7}, '{8}')
"""

DATA_UPDATE = """
UPDATE TB_POP_D_IP 
SET SUCCESS_CNT = {0}, LINE_RESP_MIN = CONCAT({1}, "ms"), 
LINE_RESP_AVG = CONCAT({2}, "ms"), LINE_RESP_MAX = CONCAT({3}, "ms"), STATUS = {4}, USER_CHK = '{5}'
WHERE LINE_NO = {6} AND LINE_IP = '{7}'
"""

DATA_LAST_AVG = """
SELECT LINE_RESP_AVG FROM TB_POP_D_IP WHERE LINE_IP = '{0}' AND LINE_NO = {1}
"""

INTERNET_INSERT = """
INSERT INTO TB_POP_I_LOG_HIST 
(SUCCESS_CNT, LINE_RESP_MIN, LINE_RESP_AVG, LINE_RESP_MAX, STATUS, USER_CHK, CRT_DT, LINE_NO, INTERNET_LINE_NO, SRC_LINE_IP) 
VALUES({0}, CONCAT({1}, "ms"), CONCAT({2}, "ms"), CONCAT({3}, "ms"), {4}, '{5}', '{6}', {7}, '{8}', '{9}')
"""

INTERNET_UPDATE = """
UPDATE TB_POP_I_LINE_DETAIL SET SUCCESS_CNT = {0}, LINE_RESP_MIN = CONCAT({1}, "ms"), LINE_RESP_AVG = CONCAT({2}, "ms"), 
LINE_RESP_MAX = CONCAT({3}, "ms"), STATUS = {4}, USER_CHK = '{5}' 
WHERE SRC_LINE_IP = '{6}'
"""

INTERNET_LAST_AVG = """
SELECT LINE_RESP_AVG FROM TB_POP_I_LINE_DETAIL WHERE SRC_LINE_IP = '{0}' AND LINE_D_NO = {1}
"""

EVT_UPDATE = """
UPDATE TB_EVT_LINE_DETAIL SET SUCCESS_CNT = {0}, LINE_RESP_MIN = CONCAT({1}, "ms"), LINE_RESP_AVG = CONCAT({2}, "ms"), 
LINE_RESP_MAX = CONCAT({3}, "ms"), STATUS = {4}, LINE_USE_YN = '{5}' 
WHERE LINE_IP = '{6}'
"""

EVT_LAST_AVG = """
SELECT LINE_RESP_AVG FROM TB_EVT_LINE_DETAIL WHERE LINE_IP = '{0}' AND LINE_NO = {1}
"""